# Note: Due to https://github.com/gotify/server/issues/350 this Dockerfile
is more limited than the default. Notably, this issue prevents configuring
a HEALTHCHECK directive.
FROM arm32v7/debian:stable-slim
WORKDIR /app
ADD gotify-app /app/
EXPOSE 80
ENTRYPOINT ["./gotify-app"]
