package config

const (
	EnvLogLevel                         = "GOTIFY_LOGLEVEL"
	EnvServerKeepAlivePeriodSeconds     = "GOTIFY_SERVER_KEEPALIVEPERIODSECONDS"
	EnvServerListenAddr                 = "GOTIFY_SERVER_LISTENADDR"
	EnvServerPort                       = "GOTIFY_SERVER_PORT"
	EnvServerSSLEnabled                 = "GOTIFY_SERVER_SSL_ENABLED"
	EnvServerSSLRedirectToHTTPS         = "GOTIFY_SERVER_SSL_REDIRECTTOHTTPS"
	EnvServerSSLListenAddr              = "GOTIFY_SERVER_SSL_LISTENADDR"
	EnvServerSSLPort                    = "GOTIFY_SERVER_SSL_PORT"
	EnvServerSSLCertFile                = "GOTIFY_SERVER_SSL_CERTFILE"
	EnvServerSSLCertKey                 = "GOTIFY_SERVER_SSL_CERTKEY"
	EnvServerSSLLetsEncryptEnabled      = "GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED"
	EnvServerSSLLetsEncryptAcceptTOS    = "GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS"
	EnvServerSSLLetsEncryptCache        = "GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE"
	EnvServerSSLLetsEncryptDirectoryURL = "GOTIFY_SERVER_SSL_LETSENCRYPT_DIRECTORYURL"
	EnvServerSSLLetsEncryptHosts        = "GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS"
	EnvServerResponseHeaders            = "GOTIFY_SERVER_RESPONSEHEADERS"
	EnvServerStreamPingPeriodSeconds    = "GOTIFY_SERVER_STREAM_PINGPERIODSECONDS"
	EnvServerStreamAllowedOrigins       = "GOTIFY_SERVER_STREAM_ALLOWEDORIGINS"
	EnvServerCorsAllowOrigins           = "GOTIFY_SERVER_CORS_ALLOWORIGINS"
	EnvServerCorsAllowMethods           = "GOTIFY_SERVER_CORS_ALLOWMETHODS"
	EnvServerCorsAllowHeaders           = "GOTIFY_SERVER_CORS_ALLOWHEADERS"
	EnvServerTrustedProxies             = "GOTIFY_SERVER_TRUSTEDPROXIES"
	EnvServerSecureCookie               = "GOTIFY_SERVER_SECURECOOKIE"
	EnvDatabaseDialect                  = "GOTIFY_DATABASE_DIALECT"
	EnvDatabaseConnection               = "GOTIFY_DATABASE_CONNECTION"
	EnvDefaultUserName                  = "GOTIFY_DEFAULTUSER_NAME"
	EnvDefaultUserPass                  = "GOTIFY_DEFAULTUSER_PASS"
	EnvPassStrength                     = "GOTIFY_PASSSTRENGTH"
	EnvUploadedImagesDir                = "GOTIFY_UPLOADEDIMAGESDIR"
	EnvPluginsDir                       = "GOTIFY_PLUGINSDIR"
	EnvRegistration                     = "GOTIFY_REGISTRATION"
	EnvOIDCEnabled                      = "GOTIFY_OIDC_ENABLED"
	EnvOIDCIssuer                       = "GOTIFY_OIDC_ISSUER"
	EnvOIDCClientID                     = "GOTIFY_OIDC_CLIENTID"
	EnvOIDCClientSecret                 = "GOTIFY_OIDC_CLIENTSECRET"
	EnvOIDCUsernameClaim                = "GOTIFY_OIDC_USERNAMECLAIM"
	EnvOIDCRedirectURL                  = "GOTIFY_OIDC_REDIRECTURL"
	EnvOIDCAutoRegister                 = "GOTIFY_OIDC_AUTOREGISTER"
	EnvOIDCLinkByUsername               = "GOTIFY_OIDC_LINK_BY_USERNAME"
	EnvOIDCScopes                       = "GOTIFY_OIDC_SCOPES"
	EnvNoColor                          = "NOCOLOR"
)
